# Change these first
owner: thejoker-dev # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Networkerd.cl
    url: https://networkerd.cl
  - name: Savethedate.cl
    url: https://www.savethedate.cl
  - name: Pollosro.cl
    url: https://www.pollosro.cl
  - name: Maoristore.cl
    url: https://maoristore.cl
  - name: Muyvesta.com
    url: https://maoristore.cl
  - name: Technasis.cl
    url: https://www.technasis.cl
  - name: Luminbarber.cl
    url: https://luminbarber.networkerd.cl

assignees:
  - thejoker-dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.networkerd.cl
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Server Status
  introTitle: "**Server Status** is a uptime monitor and status page."
  introMessage: This information page which uses **real-time** data from Networker Technology Servers (Actions, Issues, and Pages). [**More information**](https://networkerd.cl)
  navbar:
    - title: Server Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
